global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'node'
    metrics_path: /metrics
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['fastapi:8000']
