"""empty message

Revision ID: 75b464091348
Revises: 4022ad43a388
Create Date: 2023-12-03 19:36:37.244088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b464091348'
down_revision: Union[str, None] = '4022ad43a388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lots', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=750),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lots', 'description',
               existing_type=sa.String(length=750),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
